### ISSUE TITLE
Bug: Cannot Edit Card once added to lovelace

### ISSUE THREAD

**Issue by fortepc** [custom-cards/dual-gauge-card#23]
After adding this card to my UI, then attempting to edit the card by clicking edit, it does not open the card configuration options, it does not appear to respond at all. 

When I open chrome's console this is what appears when I try to click edit. I tried to fully expand it, but it seems to be looping or something because as soon as I expand it it flickers and re-appears without being expanded. I had to be really quick on the trigger to grab this screenshot. 

![2020-02-13 20_27_31-Window](https://user-images.githubusercontent.com/26149601/74493180-591c1280-4e9f-11ea-8388-c369631a98b5.png)

I also verified this is the only card being affected.

**Comment by fortepc** [comment]
Oh wow, and another thing, if I try to open my raw config editor, it opens but is totally blank. Deleting the card seems to be the only thing to get things back again.

**Comment by Syralist** [comment]
Same problem here.

**Comment by Rocka84** [comment]
Hi!
Sorry for the delay, I just recently began to take care of this card again.

I'm still using yaml files only to configure lovelace so I can't really test this at the moment. But I think @Syralist could be right and this was related to #22 which is fixed by now.
Can anyone confirm this or is this bug still present?
